name: md
channels:
  - defaults
dependencies:
  - python=3.6.8
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - jupyter
  - pandas
  - pip
  - pip:
    - ase
    - asap3
    - amp-atomistics
    - tensorflow==2.0.0-beta1
